// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoadBalancer.proto

package comm;

public final class LoadBalancer {
  private LoadBalancer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code comm.JobType}
   */
  public enum JobType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TIMED_JOB = 1;</code>
     *
     * <pre>
     ** Send a command to return after a specified interval 
     * </pre>
     */
    TIMED_JOB(0, 1),
    ;

    /**
     * <code>TIMED_JOB = 1;</code>
     *
     * <pre>
     ** Send a command to return after a specified interval 
     * </pre>
     */
    public static final int TIMED_JOB_VALUE = 1;


    public final int getNumber() { return value; }

    public static JobType valueOf(int value) {
      switch (value) {
        case 1: return TIMED_JOB;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<JobType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<JobType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<JobType>() {
            public JobType findValueByNumber(int number) {
              return JobType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return comm.LoadBalancer.getDescriptor().getEnumTypes().get(0);
    }

    private static final JobType[] VALUES = values();

    public static JobType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private JobType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:comm.JobType)
  }

  public interface ClientRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .comm.JobType t = 1;
    /**
     * <code>optional .comm.JobType t = 1;</code>
     */
    boolean hasT();
    /**
     * <code>optional .comm.JobType t = 1;</code>
     */
    comm.LoadBalancer.JobType getT();

    // optional int32 jobID = 2;
    /**
     * <code>optional int32 jobID = 2;</code>
     */
    boolean hasJobID();
    /**
     * <code>optional int32 jobID = 2;</code>
     */
    int getJobID();

    // optional int64 sendTime = 3;
    /**
     * <code>optional int64 sendTime = 3;</code>
     */
    boolean hasSendTime();
    /**
     * <code>optional int64 sendTime = 3;</code>
     */
    long getSendTime();
  }
  /**
   * Protobuf type {@code comm.ClientRequest}
   *
   * <pre>
   ** Request from client -&gt; centralized server 
   * </pre>
   */
  public static final class ClientRequest extends
      com.google.protobuf.GeneratedMessage
      implements ClientRequestOrBuilder {
    // Use ClientRequest.newBuilder() to construct.
    private ClientRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ClientRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ClientRequest defaultInstance;
    public static ClientRequest getDefaultInstance() {
      return defaultInstance;
    }

    public ClientRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ClientRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              comm.LoadBalancer.JobType value = comm.LoadBalancer.JobType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                t_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              jobID_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              sendTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return comm.LoadBalancer.internal_static_comm_ClientRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return comm.LoadBalancer.internal_static_comm_ClientRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              comm.LoadBalancer.ClientRequest.class, comm.LoadBalancer.ClientRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<ClientRequest> PARSER =
        new com.google.protobuf.AbstractParser<ClientRequest>() {
      public ClientRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ClientRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .comm.JobType t = 1;
    public static final int T_FIELD_NUMBER = 1;
    private comm.LoadBalancer.JobType t_;
    /**
     * <code>optional .comm.JobType t = 1;</code>
     */
    public boolean hasT() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .comm.JobType t = 1;</code>
     */
    public comm.LoadBalancer.JobType getT() {
      return t_;
    }

    // optional int32 jobID = 2;
    public static final int JOBID_FIELD_NUMBER = 2;
    private int jobID_;
    /**
     * <code>optional int32 jobID = 2;</code>
     */
    public boolean hasJobID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 jobID = 2;</code>
     */
    public int getJobID() {
      return jobID_;
    }

    // optional int64 sendTime = 3;
    public static final int SENDTIME_FIELD_NUMBER = 3;
    private long sendTime_;
    /**
     * <code>optional int64 sendTime = 3;</code>
     */
    public boolean hasSendTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 sendTime = 3;</code>
     */
    public long getSendTime() {
      return sendTime_;
    }

    private void initFields() {
      t_ = comm.LoadBalancer.JobType.TIMED_JOB;
      jobID_ = 0;
      sendTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, t_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, jobID_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, sendTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, t_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, jobID_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, sendTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static comm.LoadBalancer.ClientRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static comm.LoadBalancer.ClientRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static comm.LoadBalancer.ClientRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static comm.LoadBalancer.ClientRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static comm.LoadBalancer.ClientRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static comm.LoadBalancer.ClientRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static comm.LoadBalancer.ClientRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static comm.LoadBalancer.ClientRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static comm.LoadBalancer.ClientRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static comm.LoadBalancer.ClientRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(comm.LoadBalancer.ClientRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code comm.ClientRequest}
     *
     * <pre>
     ** Request from client -&gt; centralized server 
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements comm.LoadBalancer.ClientRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return comm.LoadBalancer.internal_static_comm_ClientRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return comm.LoadBalancer.internal_static_comm_ClientRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                comm.LoadBalancer.ClientRequest.class, comm.LoadBalancer.ClientRequest.Builder.class);
      }

      // Construct using comm.LoadBalancer.ClientRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        t_ = comm.LoadBalancer.JobType.TIMED_JOB;
        bitField0_ = (bitField0_ & ~0x00000001);
        jobID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        sendTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return comm.LoadBalancer.internal_static_comm_ClientRequest_descriptor;
      }

      public comm.LoadBalancer.ClientRequest getDefaultInstanceForType() {
        return comm.LoadBalancer.ClientRequest.getDefaultInstance();
      }

      public comm.LoadBalancer.ClientRequest build() {
        comm.LoadBalancer.ClientRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public comm.LoadBalancer.ClientRequest buildPartial() {
        comm.LoadBalancer.ClientRequest result = new comm.LoadBalancer.ClientRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.t_ = t_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.jobID_ = jobID_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sendTime_ = sendTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof comm.LoadBalancer.ClientRequest) {
          return mergeFrom((comm.LoadBalancer.ClientRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(comm.LoadBalancer.ClientRequest other) {
        if (other == comm.LoadBalancer.ClientRequest.getDefaultInstance()) return this;
        if (other.hasT()) {
          setT(other.getT());
        }
        if (other.hasJobID()) {
          setJobID(other.getJobID());
        }
        if (other.hasSendTime()) {
          setSendTime(other.getSendTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        comm.LoadBalancer.ClientRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (comm.LoadBalancer.ClientRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .comm.JobType t = 1;
      private comm.LoadBalancer.JobType t_ = comm.LoadBalancer.JobType.TIMED_JOB;
      /**
       * <code>optional .comm.JobType t = 1;</code>
       */
      public boolean hasT() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .comm.JobType t = 1;</code>
       */
      public comm.LoadBalancer.JobType getT() {
        return t_;
      }
      /**
       * <code>optional .comm.JobType t = 1;</code>
       */
      public Builder setT(comm.LoadBalancer.JobType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        t_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .comm.JobType t = 1;</code>
       */
      public Builder clearT() {
        bitField0_ = (bitField0_ & ~0x00000001);
        t_ = comm.LoadBalancer.JobType.TIMED_JOB;
        onChanged();
        return this;
      }

      // optional int32 jobID = 2;
      private int jobID_ ;
      /**
       * <code>optional int32 jobID = 2;</code>
       */
      public boolean hasJobID() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 jobID = 2;</code>
       */
      public int getJobID() {
        return jobID_;
      }
      /**
       * <code>optional int32 jobID = 2;</code>
       */
      public Builder setJobID(int value) {
        bitField0_ |= 0x00000002;
        jobID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 jobID = 2;</code>
       */
      public Builder clearJobID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        jobID_ = 0;
        onChanged();
        return this;
      }

      // optional int64 sendTime = 3;
      private long sendTime_ ;
      /**
       * <code>optional int64 sendTime = 3;</code>
       */
      public boolean hasSendTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 sendTime = 3;</code>
       */
      public long getSendTime() {
        return sendTime_;
      }
      /**
       * <code>optional int64 sendTime = 3;</code>
       */
      public Builder setSendTime(long value) {
        bitField0_ |= 0x00000004;
        sendTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 sendTime = 3;</code>
       */
      public Builder clearSendTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sendTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:comm.ClientRequest)
    }

    static {
      defaultInstance = new ClientRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:comm.ClientRequest)
  }

  public interface ClientResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 jobID = 1;
    /**
     * <code>optional int32 jobID = 1;</code>
     */
    boolean hasJobID();
    /**
     * <code>optional int32 jobID = 1;</code>
     */
    int getJobID();

    // optional int64 responseDispatchTime = 2;
    /**
     * <code>optional int64 responseDispatchTime = 2;</code>
     */
    boolean hasResponseDispatchTime();
    /**
     * <code>optional int64 responseDispatchTime = 2;</code>
     */
    long getResponseDispatchTime();
  }
  /**
   * Protobuf type {@code comm.ClientResponse}
   *
   * <pre>
   ** Response from centralized server -&gt; client 
   * </pre>
   */
  public static final class ClientResponse extends
      com.google.protobuf.GeneratedMessage
      implements ClientResponseOrBuilder {
    // Use ClientResponse.newBuilder() to construct.
    private ClientResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ClientResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ClientResponse defaultInstance;
    public static ClientResponse getDefaultInstance() {
      return defaultInstance;
    }

    public ClientResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ClientResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              jobID_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              responseDispatchTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return comm.LoadBalancer.internal_static_comm_ClientResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return comm.LoadBalancer.internal_static_comm_ClientResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              comm.LoadBalancer.ClientResponse.class, comm.LoadBalancer.ClientResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<ClientResponse> PARSER =
        new com.google.protobuf.AbstractParser<ClientResponse>() {
      public ClientResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ClientResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 jobID = 1;
    public static final int JOBID_FIELD_NUMBER = 1;
    private int jobID_;
    /**
     * <code>optional int32 jobID = 1;</code>
     */
    public boolean hasJobID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 jobID = 1;</code>
     */
    public int getJobID() {
      return jobID_;
    }

    // optional int64 responseDispatchTime = 2;
    public static final int RESPONSEDISPATCHTIME_FIELD_NUMBER = 2;
    private long responseDispatchTime_;
    /**
     * <code>optional int64 responseDispatchTime = 2;</code>
     */
    public boolean hasResponseDispatchTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 responseDispatchTime = 2;</code>
     */
    public long getResponseDispatchTime() {
      return responseDispatchTime_;
    }

    private void initFields() {
      jobID_ = 0;
      responseDispatchTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, jobID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, responseDispatchTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, jobID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, responseDispatchTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static comm.LoadBalancer.ClientResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static comm.LoadBalancer.ClientResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static comm.LoadBalancer.ClientResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static comm.LoadBalancer.ClientResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static comm.LoadBalancer.ClientResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static comm.LoadBalancer.ClientResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static comm.LoadBalancer.ClientResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static comm.LoadBalancer.ClientResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static comm.LoadBalancer.ClientResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static comm.LoadBalancer.ClientResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(comm.LoadBalancer.ClientResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code comm.ClientResponse}
     *
     * <pre>
     ** Response from centralized server -&gt; client 
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements comm.LoadBalancer.ClientResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return comm.LoadBalancer.internal_static_comm_ClientResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return comm.LoadBalancer.internal_static_comm_ClientResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                comm.LoadBalancer.ClientResponse.class, comm.LoadBalancer.ClientResponse.Builder.class);
      }

      // Construct using comm.LoadBalancer.ClientResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        jobID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        responseDispatchTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return comm.LoadBalancer.internal_static_comm_ClientResponse_descriptor;
      }

      public comm.LoadBalancer.ClientResponse getDefaultInstanceForType() {
        return comm.LoadBalancer.ClientResponse.getDefaultInstance();
      }

      public comm.LoadBalancer.ClientResponse build() {
        comm.LoadBalancer.ClientResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public comm.LoadBalancer.ClientResponse buildPartial() {
        comm.LoadBalancer.ClientResponse result = new comm.LoadBalancer.ClientResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.jobID_ = jobID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.responseDispatchTime_ = responseDispatchTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof comm.LoadBalancer.ClientResponse) {
          return mergeFrom((comm.LoadBalancer.ClientResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(comm.LoadBalancer.ClientResponse other) {
        if (other == comm.LoadBalancer.ClientResponse.getDefaultInstance()) return this;
        if (other.hasJobID()) {
          setJobID(other.getJobID());
        }
        if (other.hasResponseDispatchTime()) {
          setResponseDispatchTime(other.getResponseDispatchTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        comm.LoadBalancer.ClientResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (comm.LoadBalancer.ClientResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 jobID = 1;
      private int jobID_ ;
      /**
       * <code>optional int32 jobID = 1;</code>
       */
      public boolean hasJobID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 jobID = 1;</code>
       */
      public int getJobID() {
        return jobID_;
      }
      /**
       * <code>optional int32 jobID = 1;</code>
       */
      public Builder setJobID(int value) {
        bitField0_ |= 0x00000001;
        jobID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 jobID = 1;</code>
       */
      public Builder clearJobID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        jobID_ = 0;
        onChanged();
        return this;
      }

      // optional int64 responseDispatchTime = 2;
      private long responseDispatchTime_ ;
      /**
       * <code>optional int64 responseDispatchTime = 2;</code>
       */
      public boolean hasResponseDispatchTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 responseDispatchTime = 2;</code>
       */
      public long getResponseDispatchTime() {
        return responseDispatchTime_;
      }
      /**
       * <code>optional int64 responseDispatchTime = 2;</code>
       */
      public Builder setResponseDispatchTime(long value) {
        bitField0_ |= 0x00000002;
        responseDispatchTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 responseDispatchTime = 2;</code>
       */
      public Builder clearResponseDispatchTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        responseDispatchTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:comm.ClientResponse)
    }

    static {
      defaultInstance = new ClientResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:comm.ClientResponse)
  }

  public interface BalancerRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .comm.JobType t = 1;
    /**
     * <code>optional .comm.JobType t = 1;</code>
     */
    boolean hasT();
    /**
     * <code>optional .comm.JobType t = 1;</code>
     */
    comm.LoadBalancer.JobType getT();

    // optional int32 jobID = 2;
    /**
     * <code>optional int32 jobID = 2;</code>
     */
    boolean hasJobID();
    /**
     * <code>optional int32 jobID = 2;</code>
     */
    int getJobID();

    // optional int64 sendTime = 3;
    /**
     * <code>optional int64 sendTime = 3;</code>
     */
    boolean hasSendTime();
    /**
     * <code>optional int64 sendTime = 3;</code>
     */
    long getSendTime();
  }
  /**
   * Protobuf type {@code comm.BalancerRequest}
   *
   * <pre>
   ** Request from centralized balancer server -&gt; worker node 
   * </pre>
   */
  public static final class BalancerRequest extends
      com.google.protobuf.GeneratedMessage
      implements BalancerRequestOrBuilder {
    // Use BalancerRequest.newBuilder() to construct.
    private BalancerRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BalancerRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BalancerRequest defaultInstance;
    public static BalancerRequest getDefaultInstance() {
      return defaultInstance;
    }

    public BalancerRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BalancerRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              comm.LoadBalancer.JobType value = comm.LoadBalancer.JobType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                t_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              jobID_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              sendTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return comm.LoadBalancer.internal_static_comm_BalancerRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return comm.LoadBalancer.internal_static_comm_BalancerRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              comm.LoadBalancer.BalancerRequest.class, comm.LoadBalancer.BalancerRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<BalancerRequest> PARSER =
        new com.google.protobuf.AbstractParser<BalancerRequest>() {
      public BalancerRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BalancerRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BalancerRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .comm.JobType t = 1;
    public static final int T_FIELD_NUMBER = 1;
    private comm.LoadBalancer.JobType t_;
    /**
     * <code>optional .comm.JobType t = 1;</code>
     */
    public boolean hasT() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .comm.JobType t = 1;</code>
     */
    public comm.LoadBalancer.JobType getT() {
      return t_;
    }

    // optional int32 jobID = 2;
    public static final int JOBID_FIELD_NUMBER = 2;
    private int jobID_;
    /**
     * <code>optional int32 jobID = 2;</code>
     */
    public boolean hasJobID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 jobID = 2;</code>
     */
    public int getJobID() {
      return jobID_;
    }

    // optional int64 sendTime = 3;
    public static final int SENDTIME_FIELD_NUMBER = 3;
    private long sendTime_;
    /**
     * <code>optional int64 sendTime = 3;</code>
     */
    public boolean hasSendTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 sendTime = 3;</code>
     */
    public long getSendTime() {
      return sendTime_;
    }

    private void initFields() {
      t_ = comm.LoadBalancer.JobType.TIMED_JOB;
      jobID_ = 0;
      sendTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, t_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, jobID_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, sendTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, t_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, jobID_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, sendTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static comm.LoadBalancer.BalancerRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static comm.LoadBalancer.BalancerRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static comm.LoadBalancer.BalancerRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static comm.LoadBalancer.BalancerRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static comm.LoadBalancer.BalancerRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static comm.LoadBalancer.BalancerRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static comm.LoadBalancer.BalancerRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static comm.LoadBalancer.BalancerRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static comm.LoadBalancer.BalancerRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static comm.LoadBalancer.BalancerRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(comm.LoadBalancer.BalancerRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code comm.BalancerRequest}
     *
     * <pre>
     ** Request from centralized balancer server -&gt; worker node 
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements comm.LoadBalancer.BalancerRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return comm.LoadBalancer.internal_static_comm_BalancerRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return comm.LoadBalancer.internal_static_comm_BalancerRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                comm.LoadBalancer.BalancerRequest.class, comm.LoadBalancer.BalancerRequest.Builder.class);
      }

      // Construct using comm.LoadBalancer.BalancerRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        t_ = comm.LoadBalancer.JobType.TIMED_JOB;
        bitField0_ = (bitField0_ & ~0x00000001);
        jobID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        sendTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return comm.LoadBalancer.internal_static_comm_BalancerRequest_descriptor;
      }

      public comm.LoadBalancer.BalancerRequest getDefaultInstanceForType() {
        return comm.LoadBalancer.BalancerRequest.getDefaultInstance();
      }

      public comm.LoadBalancer.BalancerRequest build() {
        comm.LoadBalancer.BalancerRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public comm.LoadBalancer.BalancerRequest buildPartial() {
        comm.LoadBalancer.BalancerRequest result = new comm.LoadBalancer.BalancerRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.t_ = t_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.jobID_ = jobID_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sendTime_ = sendTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof comm.LoadBalancer.BalancerRequest) {
          return mergeFrom((comm.LoadBalancer.BalancerRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(comm.LoadBalancer.BalancerRequest other) {
        if (other == comm.LoadBalancer.BalancerRequest.getDefaultInstance()) return this;
        if (other.hasT()) {
          setT(other.getT());
        }
        if (other.hasJobID()) {
          setJobID(other.getJobID());
        }
        if (other.hasSendTime()) {
          setSendTime(other.getSendTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        comm.LoadBalancer.BalancerRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (comm.LoadBalancer.BalancerRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .comm.JobType t = 1;
      private comm.LoadBalancer.JobType t_ = comm.LoadBalancer.JobType.TIMED_JOB;
      /**
       * <code>optional .comm.JobType t = 1;</code>
       */
      public boolean hasT() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .comm.JobType t = 1;</code>
       */
      public comm.LoadBalancer.JobType getT() {
        return t_;
      }
      /**
       * <code>optional .comm.JobType t = 1;</code>
       */
      public Builder setT(comm.LoadBalancer.JobType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        t_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .comm.JobType t = 1;</code>
       */
      public Builder clearT() {
        bitField0_ = (bitField0_ & ~0x00000001);
        t_ = comm.LoadBalancer.JobType.TIMED_JOB;
        onChanged();
        return this;
      }

      // optional int32 jobID = 2;
      private int jobID_ ;
      /**
       * <code>optional int32 jobID = 2;</code>
       */
      public boolean hasJobID() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 jobID = 2;</code>
       */
      public int getJobID() {
        return jobID_;
      }
      /**
       * <code>optional int32 jobID = 2;</code>
       */
      public Builder setJobID(int value) {
        bitField0_ |= 0x00000002;
        jobID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 jobID = 2;</code>
       */
      public Builder clearJobID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        jobID_ = 0;
        onChanged();
        return this;
      }

      // optional int64 sendTime = 3;
      private long sendTime_ ;
      /**
       * <code>optional int64 sendTime = 3;</code>
       */
      public boolean hasSendTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 sendTime = 3;</code>
       */
      public long getSendTime() {
        return sendTime_;
      }
      /**
       * <code>optional int64 sendTime = 3;</code>
       */
      public Builder setSendTime(long value) {
        bitField0_ |= 0x00000004;
        sendTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 sendTime = 3;</code>
       */
      public Builder clearSendTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sendTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:comm.BalancerRequest)
    }

    static {
      defaultInstance = new BalancerRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:comm.BalancerRequest)
  }

  public interface BalancerResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .comm.JobType t = 1;
    /**
     * <code>optional .comm.JobType t = 1;</code>
     */
    boolean hasT();
    /**
     * <code>optional .comm.JobType t = 1;</code>
     */
    comm.LoadBalancer.JobType getT();

    // optional int32 jobID = 2;
    /**
     * <code>optional int32 jobID = 2;</code>
     */
    boolean hasJobID();
    /**
     * <code>optional int32 jobID = 2;</code>
     */
    int getJobID();

    // optional int64 responseDispatchTime = 3;
    /**
     * <code>optional int64 responseDispatchTime = 3;</code>
     */
    boolean hasResponseDispatchTime();
    /**
     * <code>optional int64 responseDispatchTime = 3;</code>
     */
    long getResponseDispatchTime();
  }
  /**
   * Protobuf type {@code comm.BalancerResponse}
   *
   * <pre>
   ** Response from worker node -&gt; centralized balancer server 
   * </pre>
   */
  public static final class BalancerResponse extends
      com.google.protobuf.GeneratedMessage
      implements BalancerResponseOrBuilder {
    // Use BalancerResponse.newBuilder() to construct.
    private BalancerResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BalancerResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BalancerResponse defaultInstance;
    public static BalancerResponse getDefaultInstance() {
      return defaultInstance;
    }

    public BalancerResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BalancerResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              comm.LoadBalancer.JobType value = comm.LoadBalancer.JobType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                t_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              jobID_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              responseDispatchTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return comm.LoadBalancer.internal_static_comm_BalancerResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return comm.LoadBalancer.internal_static_comm_BalancerResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              comm.LoadBalancer.BalancerResponse.class, comm.LoadBalancer.BalancerResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<BalancerResponse> PARSER =
        new com.google.protobuf.AbstractParser<BalancerResponse>() {
      public BalancerResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BalancerResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BalancerResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .comm.JobType t = 1;
    public static final int T_FIELD_NUMBER = 1;
    private comm.LoadBalancer.JobType t_;
    /**
     * <code>optional .comm.JobType t = 1;</code>
     */
    public boolean hasT() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .comm.JobType t = 1;</code>
     */
    public comm.LoadBalancer.JobType getT() {
      return t_;
    }

    // optional int32 jobID = 2;
    public static final int JOBID_FIELD_NUMBER = 2;
    private int jobID_;
    /**
     * <code>optional int32 jobID = 2;</code>
     */
    public boolean hasJobID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 jobID = 2;</code>
     */
    public int getJobID() {
      return jobID_;
    }

    // optional int64 responseDispatchTime = 3;
    public static final int RESPONSEDISPATCHTIME_FIELD_NUMBER = 3;
    private long responseDispatchTime_;
    /**
     * <code>optional int64 responseDispatchTime = 3;</code>
     */
    public boolean hasResponseDispatchTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 responseDispatchTime = 3;</code>
     */
    public long getResponseDispatchTime() {
      return responseDispatchTime_;
    }

    private void initFields() {
      t_ = comm.LoadBalancer.JobType.TIMED_JOB;
      jobID_ = 0;
      responseDispatchTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, t_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, jobID_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, responseDispatchTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, t_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, jobID_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, responseDispatchTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static comm.LoadBalancer.BalancerResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static comm.LoadBalancer.BalancerResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static comm.LoadBalancer.BalancerResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static comm.LoadBalancer.BalancerResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static comm.LoadBalancer.BalancerResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static comm.LoadBalancer.BalancerResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static comm.LoadBalancer.BalancerResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static comm.LoadBalancer.BalancerResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static comm.LoadBalancer.BalancerResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static comm.LoadBalancer.BalancerResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(comm.LoadBalancer.BalancerResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code comm.BalancerResponse}
     *
     * <pre>
     ** Response from worker node -&gt; centralized balancer server 
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements comm.LoadBalancer.BalancerResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return comm.LoadBalancer.internal_static_comm_BalancerResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return comm.LoadBalancer.internal_static_comm_BalancerResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                comm.LoadBalancer.BalancerResponse.class, comm.LoadBalancer.BalancerResponse.Builder.class);
      }

      // Construct using comm.LoadBalancer.BalancerResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        t_ = comm.LoadBalancer.JobType.TIMED_JOB;
        bitField0_ = (bitField0_ & ~0x00000001);
        jobID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        responseDispatchTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return comm.LoadBalancer.internal_static_comm_BalancerResponse_descriptor;
      }

      public comm.LoadBalancer.BalancerResponse getDefaultInstanceForType() {
        return comm.LoadBalancer.BalancerResponse.getDefaultInstance();
      }

      public comm.LoadBalancer.BalancerResponse build() {
        comm.LoadBalancer.BalancerResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public comm.LoadBalancer.BalancerResponse buildPartial() {
        comm.LoadBalancer.BalancerResponse result = new comm.LoadBalancer.BalancerResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.t_ = t_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.jobID_ = jobID_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.responseDispatchTime_ = responseDispatchTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof comm.LoadBalancer.BalancerResponse) {
          return mergeFrom((comm.LoadBalancer.BalancerResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(comm.LoadBalancer.BalancerResponse other) {
        if (other == comm.LoadBalancer.BalancerResponse.getDefaultInstance()) return this;
        if (other.hasT()) {
          setT(other.getT());
        }
        if (other.hasJobID()) {
          setJobID(other.getJobID());
        }
        if (other.hasResponseDispatchTime()) {
          setResponseDispatchTime(other.getResponseDispatchTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        comm.LoadBalancer.BalancerResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (comm.LoadBalancer.BalancerResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .comm.JobType t = 1;
      private comm.LoadBalancer.JobType t_ = comm.LoadBalancer.JobType.TIMED_JOB;
      /**
       * <code>optional .comm.JobType t = 1;</code>
       */
      public boolean hasT() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .comm.JobType t = 1;</code>
       */
      public comm.LoadBalancer.JobType getT() {
        return t_;
      }
      /**
       * <code>optional .comm.JobType t = 1;</code>
       */
      public Builder setT(comm.LoadBalancer.JobType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        t_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .comm.JobType t = 1;</code>
       */
      public Builder clearT() {
        bitField0_ = (bitField0_ & ~0x00000001);
        t_ = comm.LoadBalancer.JobType.TIMED_JOB;
        onChanged();
        return this;
      }

      // optional int32 jobID = 2;
      private int jobID_ ;
      /**
       * <code>optional int32 jobID = 2;</code>
       */
      public boolean hasJobID() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 jobID = 2;</code>
       */
      public int getJobID() {
        return jobID_;
      }
      /**
       * <code>optional int32 jobID = 2;</code>
       */
      public Builder setJobID(int value) {
        bitField0_ |= 0x00000002;
        jobID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 jobID = 2;</code>
       */
      public Builder clearJobID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        jobID_ = 0;
        onChanged();
        return this;
      }

      // optional int64 responseDispatchTime = 3;
      private long responseDispatchTime_ ;
      /**
       * <code>optional int64 responseDispatchTime = 3;</code>
       */
      public boolean hasResponseDispatchTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 responseDispatchTime = 3;</code>
       */
      public long getResponseDispatchTime() {
        return responseDispatchTime_;
      }
      /**
       * <code>optional int64 responseDispatchTime = 3;</code>
       */
      public Builder setResponseDispatchTime(long value) {
        bitField0_ |= 0x00000004;
        responseDispatchTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 responseDispatchTime = 3;</code>
       */
      public Builder clearResponseDispatchTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        responseDispatchTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:comm.BalancerResponse)
    }

    static {
      defaultInstance = new BalancerResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:comm.BalancerResponse)
  }

  /**
   * Protobuf service {@code comm.LoadBalancerServer}
   */
  public static abstract class LoadBalancerServer
      implements com.google.protobuf.Service {
    protected LoadBalancerServer() {}

    public interface Interface {
      /**
       * <code>rpc makeRequest(.comm.ClientRequest) returns (.comm.ClientResponse);</code>
       *
       * <pre>
       ** Issue a request to the centralized load balancer 
       * </pre>
       */
      public abstract void makeRequest(
          com.google.protobuf.RpcController controller,
          comm.LoadBalancer.ClientRequest request,
          com.google.protobuf.RpcCallback<comm.LoadBalancer.ClientResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new LoadBalancerServer() {
        @java.lang.Override
        public  void makeRequest(
            com.google.protobuf.RpcController controller,
            comm.LoadBalancer.ClientRequest request,
            com.google.protobuf.RpcCallback<comm.LoadBalancer.ClientResponse> done) {
          impl.makeRequest(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.makeRequest(controller, (comm.LoadBalancer.ClientRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return comm.LoadBalancer.ClientRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return comm.LoadBalancer.ClientResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc makeRequest(.comm.ClientRequest) returns (.comm.ClientResponse);</code>
     *
     * <pre>
     ** Issue a request to the centralized load balancer 
     * </pre>
     */
    public abstract void makeRequest(
        com.google.protobuf.RpcController controller,
        comm.LoadBalancer.ClientRequest request,
        com.google.protobuf.RpcCallback<comm.LoadBalancer.ClientResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return comm.LoadBalancer.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.makeRequest(controller, (comm.LoadBalancer.ClientRequest)request,
            com.google.protobuf.RpcUtil.<comm.LoadBalancer.ClientResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return comm.LoadBalancer.ClientRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return comm.LoadBalancer.ClientResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends comm.LoadBalancer.LoadBalancerServer implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void makeRequest(
          com.google.protobuf.RpcController controller,
          comm.LoadBalancer.ClientRequest request,
          com.google.protobuf.RpcCallback<comm.LoadBalancer.ClientResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          comm.LoadBalancer.ClientResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            comm.LoadBalancer.ClientResponse.class,
            comm.LoadBalancer.ClientResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public comm.LoadBalancer.ClientResponse makeRequest(
          com.google.protobuf.RpcController controller,
          comm.LoadBalancer.ClientRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public comm.LoadBalancer.ClientResponse makeRequest(
          com.google.protobuf.RpcController controller,
          comm.LoadBalancer.ClientRequest request)
          throws com.google.protobuf.ServiceException {
        return (comm.LoadBalancer.ClientResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          comm.LoadBalancer.ClientResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:comm.LoadBalancerServer)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_comm_ClientRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_comm_ClientRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_comm_ClientResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_comm_ClientResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_comm_BalancerRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_comm_BalancerRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_comm_BalancerResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_comm_BalancerResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022LoadBalancer.proto\022\004comm\"J\n\rClientRequ" +
      "est\022\030\n\001t\030\001 \001(\0162\r.comm.JobType\022\r\n\005jobID\030\002" +
      " \001(\005\022\020\n\010sendTime\030\003 \001(\003\"=\n\016ClientResponse" +
      "\022\r\n\005jobID\030\001 \001(\005\022\034\n\024responseDispatchTime\030" +
      "\002 \001(\003\"L\n\017BalancerRequest\022\030\n\001t\030\001 \001(\0162\r.co" +
      "mm.JobType\022\r\n\005jobID\030\002 \001(\005\022\020\n\010sendTime\030\003 " +
      "\001(\003\"Y\n\020BalancerResponse\022\030\n\001t\030\001 \001(\0162\r.com" +
      "m.JobType\022\r\n\005jobID\030\002 \001(\005\022\034\n\024responseDisp" +
      "atchTime\030\003 \001(\003*\030\n\007JobType\022\r\n\tTIMED_JOB\020\001" +
      "2N\n\022LoadBalancerServer\0228\n\013makeRequest\022\023.",
      "comm.ClientRequest\032\024.comm.ClientResponse" +
      "B\003\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_comm_ClientRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_comm_ClientRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_comm_ClientRequest_descriptor,
              new java.lang.String[] { "T", "JobID", "SendTime", });
          internal_static_comm_ClientResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_comm_ClientResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_comm_ClientResponse_descriptor,
              new java.lang.String[] { "JobID", "ResponseDispatchTime", });
          internal_static_comm_BalancerRequest_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_comm_BalancerRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_comm_BalancerRequest_descriptor,
              new java.lang.String[] { "T", "JobID", "SendTime", });
          internal_static_comm_BalancerResponse_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_comm_BalancerResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_comm_BalancerResponse_descriptor,
              new java.lang.String[] { "T", "JobID", "ResponseDispatchTime", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
